version: "2"
run:
  build-tags:
    - integration
  modules-download-mode: vendor
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - goconst
    - gocritic
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nonamedreturns
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    # - tagalign
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 10
  uniq-by-line: false
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
