run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true

  skip-dirs:
    - vendor

  modules-download-mode: vendor

  # list of build tags, all linters use it. Default is empty list
  build-tags:
    - integration

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

  uniq-by-line: false

linters:
  disable-all: true
  enable:
    - golint
    - gofmt
    - gosec
    - unparam
    - goconst
    - prealloc
    - stylecheck
    - unconvert
    - staticcheck
    - gosec
    - tparallel
    - whitespace
    - revive
    - godot
    - errorlint
    - gocritic
    - errname
    - govet
    - predeclared
    - exhaustive
    - tenv
    - gofumpt
    - forcetypeassert
    - nilerr
    - errcheck
    # - promlinter this is a very nice linter, but it will most probably break things...
    # - nestif
  fast: false

issues:
  exclude-rules:
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA1019:"