run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

  modules-download-mode: vendor

  # list of build tags, all linters use it. Default is empty list
  build-tags:
    - integration

# output configuration options
output:
  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

  uniq-by-line: false

linters:
  disable-all: true
  enable:
    - gofmt
    - gosimple
    - unparam
    - goconst
    - prealloc
    - stylecheck
    - unconvert
    - unused
    - staticcheck
    - ineffassign
    - gosec
    - tparallel
    - whitespace
    - revive
    - godot
    - errorlint
    - gocritic
    - errname
    - govet
    - predeclared
    - nestif
    - exhaustive
    - tenv
    - gofumpt
    - forcetypeassert
    - nilerr
    - errcheck
    - bodyclose
    - goimports
    - durationcheck
    - errchkjson
    - sloglint
    - dupword
    - noctx
    - makezero
    - nilnil
    - reassign
    - sloglint
    - spancheck
    - testifylint
    - wastedassign
    - rowserrcheck
    - sqlclosecheck
    - goprintffuncname
    - testableexamples
    - wastedassign
    - nonamedreturns
    - perfsprint
    - dogsled
    - protogetter
    - usestdlibvars
    - testableexamples
  fast: false

issues:
  exclude-dirs:
    - vendor
  max-same-issues: 10
