version: '3.2'
services:
  harvester-ci:
    build:
      context: ./
      dockerfile: ./Dockerfile.ci
    environment:
      - CODECOV_TOKEN
    # Mount the host's docker socket into the container to allow this container to spin up other containers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Set network mode to host so all ports are mapped with the host, otherwise the tests will not be able to connect to the other containers
    network_mode: host
